spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bangoulap?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false

    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true

#  server:
#    error:
#      include-message: always
#      include-binding-errors: always
#    port: 8081

  mail:
    host: localhost
    port: 1025
    username: Hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port: 8080
